### PR TITLE
update 220523 g2t for VEP purposes

### PR DESCRIPTION
**Pull request by Yu-jinKim**
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/dias_config/21)

### CODE REVIEW

**Review by Addy81 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/dias_config/21)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @Addy81 and @Yu-jinKim)

___
*[`dias_dynamic_files.py` line 8 at r1](https://reviewable.io/reviews/eastgenomics/dias_config/21#-N2q5Cdh9Y95yj3P7zpw:-N2q5Cdh9Y95yj3P7zpx:bpup28m) ([raw file](https://github.com/eastgenomics/dias_config/blob/e8fb3745019d3c5bac9414a7d63a165319514d60/dias_dynamic_files.py#L8)):*
> ```Python
> bioinformatic_manifest = "{}:file-G961GPQ433GXkvqv2q47fy3f".format(project_id)
> # g2t 220523
> nirvana_genes2transcripts = "{}:file-GB5bV28433Gv0ygjK600kK1x".format(project_id)
> ```

Would it be too much effort to rename this to not be nirvana_genes2trascripts? And the folder in 001_Ref? 



_Code quote:_
```Python
file-GB5bV28433Gv0ygjK600kK1x
```

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/dias_config/21)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @Addy81)

___
*[`dias_dynamic_files.py` line 8 at r1](https://reviewable.io/reviews/eastgenomics/dias_config/21#-N2q5Cdh9Y95yj3P7zpw:-N2q6h7w3UNFUJ758LHs:b-896fix) ([raw file](https://github.com/eastgenomics/dias_config/blob/e8fb3745019d3c5bac9414a7d63a165319514d60/dias_dynamic_files.py#L8)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

Would it be too much effort to rename this to not be nirvana_genes2trascripts? And the folder in 001_Ref? 
</blockquote></details>

Done.

**Review by Addy81 — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/dias_config/21)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @Addy81)

**Review by Addy81 — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/dias_config/21#-:-N2q8pfz37G4J-BUmZMW:bg7igkv)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @Addy81)

**Review by Addy81 — APPROVED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/dias_config/21)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Yu-jinKim)

**Pull request merged**
